language: node_js

install:
- npm install -g npm
- cd extension; npm install; cd ..
- cd frontend; npm install; cd ..

env: # important! Without the top-level env, no job will be allowed to fail.
  - JOB_DEFAULT=test

matrix:
  fast_finish: true
  include:
    - node_js: 8
      env: TYPE=UNIT_CODESTYLE_DEPENDENCY
      script:
      - cd extension
      - npm run test
      - npm run lint
      - npm run check
      - cd ../frontend
      - npm run lint
    - node_js: 8
      env: TYPE=INTEGRATION
      script:
      - if [[ "$INTEGRATION_CREDENTIALS" ]]; then echo "${INTEGRATION_CREDENTIALS}" > .integration-credentials.js; fi
      - cd extension
      - if [[ "$INTEGRATION_CREDENTIALS" ]]; then npm run testIntegration; fi
  allow_failures:
    - node_js: 8
      env: TYPE=INTEGRATION

notifications:
  slack:
    rooms:
      secure: gTYX7Eb2QsizELvdWH9GW544IGTWeQOYornt/y8QlXqv6k0Yt+pVw3kvUNRzkp7hVS6UF37sBfibrseTjhvoQR3D6qWF5RHGwrFADMY8eWkfc4bVHmZJ32Hsrp+V4BQ8IACCdhV0vMWFx8r6rZnKe8vwovLJnB3mQUEfEV4EmcD2nc8MXPjVAXs1rCCjOywA66NpJJebM+BFGZ0NoeRPFlWgbt/I9LmwwraDlvhfal9ABEmDqJvQ8/Sbbcqx8XSPKiDnCM+x3qC68p+6956UurxlhQG0TwMeZyoZC1qVScyUPNyoIXt303Q0O0tPomrP49Mb4o1B5P6hisMd37ITv0YgRFBeYxJFxMu6YiGmX1T4w74ITVeXtfn3HIBz5E+E8WfJl6C+kVtiZC4PCjD7C/vzVf5Z9IPp/hQFpPz6skkSMvK/DmfeD0lNG7SCGq+E/coapCdh4KaM8vlC9itKGFg8+hNB0j/BWMefDx5Sh1tGm1pSMZut7M5oEpsLKqjYQKYhdcihck4S3TEv0bXIb5tKp4lJpcoNjCc7rgIx+kZjKyJMx9jJs1eDscTW0bNkh/ooAhANiCls7u1H5hlLOlcxK2aNkV1BFaIOahhsO/zoAmZeQMgHrNifgq6uv/MzCzjcXYAvQUg32TX7CxqS/SQU2+qDkuCsA3XDHyEqomg=
    on_success: change
    on_failure: always
